# Generated by Django 4.1.5 on 2023-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_genre_alter_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='star',
            field=models.FloatField(null=True),
        ),
    ]
