# Generated by Django 4.1.5 on 2023-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='actor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
