# Generated by Django 4.1.5 on 2023-01-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('devtool', models.CharField(blank=True, choices=[('django', 'django'), ('react', 'react'), ('Spring', 'Spring'), ('Node.js', 'Node.js'), ('Java', 'Java'), ('C++', 'C++')], max_length=16, null=True)),
                ('interest', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d')),
            ],
        ),
    ]
